repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-yaml
        exclude: ^venv/
    -   id: end-of-file-fixer
        exclude: ^venv/
    -   id: trailing-whitespace
        exclude: ^venv/
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        name: isort
        stages: [commit]
        entry: pipenv run isort
        types: [python]
        exclude: ^venv/
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
        name: black
        stages: [commit]
        entry: pipenv run black
        types: [python]
        exclude: ^venv/
-   repo: https://github.com/pycqa/flake8
    rev: '5.0.4'  # pick a git hash / tag to point to
    hooks:
    -   id: flake8
        name: flake8
        stages: [commit]
        entry: pipenv run flake8
        types: [python]
        exclude: ^venv/
-   repo: local
    hooks:
    -   id: mypy
        name: mypy
        stages: [commit]
        language: system
        entry: pipenv run mypy
        types: [python]
        pass_filenames: false
        exclude: ^venv/

    # -   id: pytest
    #     name: pytest
    #     stages: [commit]
    #     language: system
    #     entry: pipenv run pytest
    #     types: [python]

    # -   id: pytest-cov
    #     name: pytest
    #     stages: [push]
    #     language: system
    #     entry: pipenv run pytest --cov --cov-fail-under=100
    #     types: [python]
    #     pass_filenames: false
